AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a Site-to-Site VPN connection with BGP.

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  # Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  # Virtual Private Gateway (VGW)
  VirtualPrivateGateway:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: MyVirtualPrivateGateway

  AttachVPNGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      VpnGatewayId: !Ref VirtualPrivateGateway

  # Customer Gateway (CGW)
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: 65001
      IpAddress: 198.51.100.1 # Replace with your on-premises public IP
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: MyCustomerGateway

  # VPN Connection
  VPNConnection:
    Type: AWS::EC2::VPNConnection
    Properties:
      Type: ipsec.1
      CustomerGatewayId: !Ref CustomerGateway
      VpnGatewayId: !Ref VirtualPrivateGateway
      Options:
        StaticRoutesOnly: false
      Tags:
        - Key: Name
          Value: MyVPNConnection

  # VPN Connection Route Propagation
  VPNRoutePropagation:
    Type: AWS::EC2::VPNConnectionRoute
    Properties:
      DestinationCidrBlock: 192.168.1.0/24 # Replace with your on-premises network CIDR
      VpnConnectionId: !Ref VPNConnection

  # Route Table
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyRouteTable

  # Route Table Association
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  # VPN Gateway Route Propagation
  RoutePropagation:
    Type: AWS::EC2::VPNGatewayRoutePropagation
    Properties:
      RouteTableIds:
        - !Ref RouteTable
      VpnGatewayId: !Ref VirtualPrivateGateway

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref MyVPC

  VPNConnectionId:
    Description: VPN Connection ID
    Value: !Ref VPNConnection
