AWSTemplateFormatVersion: '2010-09-09'
Description: 'Direct Connect Configuration without Gateway'

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  # Subnet
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs]
      Tags:
        - Key: Name
          Value: MySubnet

  # Virtual Private Gateway
  MyVGW:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1
      Tags:
        - Key: Name
          Value: MyVGW

  # Attach VGW to VPC
  MyVGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      VpnGatewayId: !Ref MyVGW

  # Direct Connect Virtual Interface
  MyPrivateVirtualInterface:
    Type: AWS::DirectConnect::PrivateVirtualInterface
    Properties:
      VirtualInterfaceName: MyPrivateVIF
      ConnectionId: dxcon-xxxxxxxx  # Replace with your Direct Connect connection ID
      Vlan: 101
      Asn: 65000
      AmazonAddress: 169.254.1.1/30
      CustomerAddress: 169.254.1.2/30
      VirtualGatewayId: !Ref MyVGW
      Tags:
        - Key: Name
          Value: MyPrivateVirtualInterface

  # Route Table
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyRouteTable

  # Route Table Association
  MyRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MySubnet
      RouteTableId: !Ref MyRouteTable

  # Routes for On-Premises
  MyRouteToOnPrem:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 192.168.0.0/16  # Replace with your on-premises CIDR
      GatewayId: !Ref MyVGW
