AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an Amazon FSx for Lustre file system with S3 integration, multi-AZ setup, and multiple EC2 instances attached.

Resources:
  # VPC for FSx and EC2
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FSxVPC

  # Subnets for Multi-AZ setup
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: FSxSubnetA

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: FSxSubnetB

  # Security Group for FSx and EC2
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow FSx traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 988
          ToPort: 1023
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  # FSx for Lustre File System
  FSxFileSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      LustreConfiguration:
        ImportPath: s3://my-s3-bucket  # Replace with your S3 bucket
        ExportPath: s3://my-s3-bucket/results  # Replace with your S3 export bucket
        DeploymentType: PERSISTENT_1
        PerUnitStorageThroughput: 200
      StorageCapacity: 1200
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
      SecurityGroupIds:
        - !Ref SecurityGroup

  # EC2 Instance 1
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: my-key-pair  # Replace with your key pair name
      ImageId: ami-0c02fb55956c7d316  # Replace with a valid AMI ID
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetA
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y lustre-client
          mkdir /mnt/fsx
          mount -t lustre ${FSxFileSystem.DnsName}@tcp:/ /mnt/fsx

  # EC2 Instance 2
  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: my-key-pair  # Replace with your key pair name
      ImageId: ami-0c02fb55956c7d316  # Replace with a valid AMI ID
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          SubnetId: !Ref SubnetB
          DeviceIndex: 0
          GroupSet:
            - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install -y lustre-client
          mkdir /mnt/fsx
          mount -t lustre ${FSxFileSystem.DnsName}@tcp:/ /mnt/fsx

Outputs:
  FSxFileSystemId:
    Description: The ID of the FSx file system
    Value: !Ref FSxFileSystem

  EC2Instance1PublicIP:
    Description: Public IP address of the first EC2 instance
    Value: !GetAtt EC2Instance1.PublicIp

  EC2Instance2PublicIP:
    Description: Public IP address of the second EC2 instance
    Value: !GetAtt EC2Instance2.PublicIp
